### ISSUE TITLE
Error 404 on input.txt files

### ISSUE THREAD

**Issue by yann120** [pacso/aoc_rb#24]
Hello 
I followed the readme, add the cookie in the .env

When I run `aoc prep 2022 01` It works, I have the folder 2022/01 with the 2 files, the `solution.rb` is correct.
But inside the `input.txt` the content is `404 Not Found`
It is the same for every exercise...

Thanks :)

**Comment by pacso** [comment]
The problem statements for each day on www.adventofcode.com are available publicly without needing to log in. The `input.txt` can only be accessed once you've authenticated.

You should check your `.env` file again to ensure you've added your session cookie correctly.
